[general]
font-mono = "Adwaita Mono"

[bar]
scale = 0.8500000238418579
inset-edge = 0.25
inset-ends = 0.6000000238418579
padding = 0.4000000059604645
padding-ends = 1.0
module-gap = 0.550000011920929
background-opacity = 90
rounding = "md"
shadow = "floating"
button-variant = "basic"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "window-title",
    "systray",
]
center = ["cava"]
right = [
    "brightness",
    "keyboard-input",
    "bluetooth",
    "network",
    "volume",
    "clock",
    "notifications",
]

[styling]
scale = 1.1100000143051147

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.brightness]
label-show = false

[modules.cava]
stereo = true

[modules.clock]
icon-show = false
dropdown-show-seconds = true

[modules.hyprland-workspaces]
app-icons-show = true

[modules.keyboard-input]
icon-show = false

[modules.network]
label-show = false

[modules.notifications]
label-show = false

[modules.window-title]
label-max-length = 25

[osd]
position = "top"

[wallpaper]
transition-type = "none"
