
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Fallback for anything not explicitly listed below
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- Laptop panel (16", 1920x1200 ~141ppi) vs external (27", 1920x1080 ~82ppi):
-- at scale=1 everything renders ~1.7x smaller on the laptop than on the monitor.
-- 1.5 is a common, artifact-free fractional scale that gets it close.
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "1920x0",
    scale    = 1.25,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "0x0",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "thunar"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function ()
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)
hl.on("hyprland.start", function ()
    hl.exec_cmd("wayle panel start")
    hl.exec_cmd("copyq")  -- clipboard manager: starts monitoring clipboard + tray icon
    hl.exec_cmd("hypridle")  -- idle daemon: auto-lock/dpms-off/suspend on inactivity
    hl.exec_cmd("hyprpaper")  -- wallpaper daemon
    -- hyprpaper (v0.8.4+) has no config file anymore, wallpapers are set live via IPC.
    -- Small delay so the daemon is ready to accept the request before we call it.
    hl.exec_cmd("bash -c 'sleep 1; hyprctl hyprpaper wallpaper \"eDP-1,/home/rayxaus/Pictures/Wallpapers/test_wallpaper.jpg,cover\"; hyprctl hyprpaper wallpaper \"HDMI-A-1,/home/rayxaus/Pictures/Wallpapers/test_wallpaper.jpg,cover\"'")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity     = 0.89,
        inactive_opacity   = 0.89,
        fullscreen_opacity = 0.89,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,ru",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:caps_toggle",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Per-device config, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
-- Lower sensitivity on the main mouse (range is -1.0 .. 1.0, 0 = no change)
hl.device({
    name        = "r5-ultra-mouse",
    sensitivity = -0.6,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd(terminal .. " -e env NO_FASTFETCH=1 fish"))  -- terminal without fastfetch banner
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.kill())       -- force-kill an unresponsive window
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))  -- lock screen
-- emoji picker (macOS Cmd+Ctrl+Space equivalent). Always copies to clipboard too:
-- wtype's synthetic typing is unreliable in Chromium/Electron apps (e.g. Claude desktop)
hl.bind(mainMod .. " + grave", hl.dsp.exec_cmd("rofimoji --selector wofi --typer wtype --action type clipboard"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("copyq toggle"))  -- clipboard history (macOS Cmd+Shift+V equivalent)
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + N", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + B", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Toggle transparency of the currently focused window: by default all windows
-- are 0.89 opacity (see decoration.*_opacity below); this tags the window
-- "opaque" to override back to fully solid, and untags it to restore 0.89
hl.bind(mainMod .. " + O", hl.dsp.window.tag({ tag = "opaque" }))

-- Fullscreen (mode 2, no gaps/borders) vs Maximize (mode 1, fills screen but keeps gaps)
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = 1 }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen())

-- Window groups (tabs): put windows in one slot, cycle between them
hl.bind(mainMod .. " + G",     hl.dsp.group.toggle())
hl.bind(mainMod .. " + comma", hl.dsp.group.prev())
hl.bind(mainMod .. " + period",hl.dsp.group.next())

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch focus to the other monitor with mainMod + ALT + left/right
hl.bind(mainMod .. " + ALT + right", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mainMod .. " + ALT + left",  hl.dsp.focus({ monitor = "-1" }))

-- Move the active window to the other monitor with mainMod + ALT + SHIFT + left/right
hl.bind(mainMod .. " + ALT + SHIFT + right", hl.dsp.window.move({ monitor = "+1" }))
hl.bind(mainMod .. " + ALT + SHIFT + left",  hl.dsp.window.move({ monitor = "-1" }))

-- Move the whole current workspace to the other monitor with mainMod + SHIFT + left/right
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.workspace.move({ monitor = "+1" }))
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.workspace.move({ monitor = "-1" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Screenshots (hyprshot captures, pipes raw PNG into satty for annotation/save/copy)
-- mirrors macOS Cmd+Shift+3/4/5 muscle memory using Print instead of Super
local screenshotOut = "~/Pictures/Screenshots/screenshot-%Y-%m-%d_%H-%M-%S.png"
local regionShot  = "bash -c 'hyprshot -m region --raw -s | satty -f - -o \"" .. screenshotOut .. "\" --copy-command wl-copy'"
local outputShot  = "bash -c 'hyprshot -m output --raw -s | satty -f - -o \"" .. screenshotOut .. "\" --copy-command wl-copy'"
local windowShot  = "bash -c 'hyprshot -m window --raw -s | satty -f - -o \"" .. screenshotOut .. "\" --copy-command wl-copy'"
local quickCopy   = "hyprshot -m region --clipboard-only"  -- no editor

hl.bind("Print",             hl.dsp.exec_cmd(regionShot))
hl.bind("SHIFT + Print",     hl.dsp.exec_cmd(outputShot))
hl.bind("CTRL + Print",      hl.dsp.exec_cmd(windowShot))
hl.bind("ALT + Print",       hl.dsp.exec_cmd(quickCopy))

-- Fallback bindings: this laptop's built-in keyboard doesn't send a real "Print"
-- keysym on Fn+PrtScn (it sends XF86Calculator instead, quirky firmware) — these
-- work from any keyboard regardless of what the physical Print key does
hl.bind(mainMod .. " + X",              hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))  -- region -> clipboard
hl.bind(mainMod .. " + SHIFT + X",      hl.dsp.exec_cmd("hyprshot -m output --clipboard-only"))  -- fullscreen -> clipboard
hl.bind(mainMod .. " + ALT + X",        hl.dsp.exec_cmd(regionShot))                             -- region -> satty
hl.bind(mainMod .. " + ALT + SHIFT + X", hl.dsp.exec_cmd(outputShot))                            -- fullscreen -> satty

-- Screen recording: just launches Kooha's own GUI to pick area/mic and start recording
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("kooha"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Windows tagged "opaque" (via Super+O) override the global 0.89 opacity back to solid.
    -- NOTE: window_rule opacity is a MULTIPLIER on top of decoration.active_opacity (0.89),
    -- so to land on 1.0 we need 1/0.89 here, not 1.0 itself.
    name    = "toggle-transparency",
    match   = { tag = "opaque" },
    opacity = "1.1236 1.1236 1.1236",
})

hl.window_rule({
    -- CopyQ (clipboard history): floating, not tiled into the layout
    name  = "copyq-floating",
    match = { class = "^com.github.hluk.copyq$" },
    float = true,
    size  = "600 700",
})

hl.window_rule({
    -- satty (screenshot annotation): fixed-size floating window, not tiled into the layout
    -- (90% was too big for full-screen shots, overlapped the top bar)
    name  = "satty-floating",
    match = { class = "^com.gabm.satty$" },
    float = true,
    size  = "1400 900",
})

hl.window_rule({
    -- AyuGram: open floating and narrow instead of tiled
    -- (size matches the current on-screen size at eDP-1 scale 1.25)
    name  = "ayugram-floating",
    match = { class = "^com.ayugram.desktop$" },
    float = true,
    size  = "709 892",
})

hl.window_rule({
    -- GNOME Calculator: open floating and small
    name  = "calculator-floating",
    match = { class = "^org.gnome.Calculator$" },
    float = true,
    size  = "400 300",
})

hl.window_rule({
    -- Google Chrome: stays fully opaque, unlike everything else (which defaults to 0.89).
    -- Same compensating multiplier trick as the Super+O "opaque" tag rule above.
    name    = "chrome-opaque",
    match   = { class = "^[Gg]oogle-chrome$" },
    opacity = "1.1236 1.1236 1.1236",
})

hl.window_rule({
    -- gThumb: stays fully opaque too, like Chrome
    name    = "gthumb-opaque",
    match   = { class = "^org.gnome.gThumb$" },
    opacity = "1.1236 1.1236 1.1236",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
