[Options]
activate_item_with_single_click=true
tabs=&clipboard

[Theme]
alt_bg=#141c2c
alt_item_css=
bg=#090c13
css=
edit_bg=#141c2c
edit_fg=#c5d2e0
edit_font="Sans,11,-1,5,50,0,0,0,0,0"
fg=#c5d2e0
find_bg=#076e8a
find_fg=#ffffff
find_font="Sans,10,-1,5,50,0,0,0,0,0"
font="Sans,10,-1,5,50,0,0,0,0,0"
hover_item_css=background: #1c2c48
item_css=
notes_bg=#141c2c
notes_css=
notes_fg=#8fa2b8
notes_font="Sans,11,-1,5,50,0,0,0,0,0"
num_fg=#3a4c60
num_font="Sans,7,-1,5,25,0,0,0,0,0"
sel_bg=#090c13
sel_fg=#c5d2e0
sel_item_css=
show_number=true
show_scrollbars=true
